version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
    platform: linux/x86_64
