version: "3"

services:
  db-toby-spring:
    image: mysql:8.0.23
    container_name: db-toby-spring-vol1-ch1
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
    platform: linux/x86_64
